name: Node CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 14

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: "Setting up Node.js: ${{ matrix.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        run: npm test
