name: Node CI

on:
  push:
    tags:
      - '!*'
    branches:
      - master

jobs:
  test:
    name: 'Node.js: ${{ matrix.node-version }} | ${{ matrix.os }} | ${{ matrix.arch }}'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2      
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
        node-version:
          - 18
          - 16
          - 14
    
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
        
      - name: Check concurrency 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: "Setting up Node.js: ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        run: npm test
