name: Node CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: 'Node.js: ${{ matrix.node-version }} | ${{ matrix.os }} | ${{ matrix.arch }}'

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3      
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
        node-version:
          - 14

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: "Setting up Node.js: ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        run: npm test
